// apps/docs/example/hosts/react/Greeter.tsx
import { useState } from "react";

export interface Input {
  label: string;
  names: { id: number; text: string }[];
}

export default function Greeter({ label, names }: Input) {
  const [count, setCount] = useState(0);
  return (
    <section>
      <h1>{label}</h1>
      <button onClick={() => setCount(count + 1)}>clicked {count}</button>
      {count > 2 && <p>That is plenty.</p>}
      <ul>
        {names.map((name) => (
          <li key={name.id}>{name.text}</li>
        ))}
      </ul>
    </section>
  );
}

// apps/docs/example/hosts/angular/greeter.component.ts
import { Component, Input, signal } from "@angular/core";

@Component({
  selector: "app-greeter",
  template: `
    <section>
      <h1>{{ label }}</h1>
      <button (click)="count.update((n) => n + 1)">clicked {{ count() }}</button>
      @if (count() > 2) {
        <p>That is plenty.</p>
      }
      <ul>
        @for (name of names; track name.id) {
          <li>{{ name.text }}</li>
        }
      </ul>
    </section>
  `,
})
export class Greeter {
  @Input() label = "";
  @Input() names: { id: number; text: string }[] = [];
  protected count = signal(0);
}
