// apps/docs/example/hosts/react/Team.tsx
import { useState } from "react";
import type { Member } from "./members.ts";
import { Table } from "./Table.tsx";

export function Team({ members }: { members: Member[] }) {
  const [query, setQuery] = useState("");
  const shown = members.filter((member) => member.name.includes(query));

  return (
    <section id="team" className="panel">
      <input
        name="q"
        className="search"
        type="search"
        value={query}
        onChange={(event) => setQuery(event.target.value)}
      />
      <Table
        rows={shown}
        head={
          <>
            <th>Name</th>
            <th>Teams</th>
          </>
        }
        row={(member) => (
          <>
            <td className={member.admin ? "admin" : undefined}>{member.name}</td>
            <td>
              {member.teams.map((team) => (
                <span key={team} className="tag">
                  {team}
                </span>
              ))}
            </td>
          </>
        )}
        empty={
          query ? (
            <p className="empty">Nobody matches “{query}”.</p>
          ) : (
            <p className="empty">No members yet.</p>
          )
        }
      />
    </section>
  );
}

// apps/docs/example/hosts/angular/team.component.ts
import { NgClass } from "@angular/common";
import { Component, Input } from "@angular/core";
import { Card } from "./tags/card";
import type { Member } from "./members";

@Component({
  selector: "app-team",
  imports: [Card, NgClass],
  template: `
    <mx-card>
      <ng-container ngProjectAs="[title]">
        Team <span class="count">{{ shown.length }}</span>
      </ng-container>
      <input name="q" class="search" type="search" [value]="query" (input)="search($event)" />
      @if (shown.length) {
        <ul class="members">
          @for (member of shown; track member.id) {
            <li [ngClass]="{ admin: member.admin }">
              {{ member.name }}
              @for (team of member.teams; track team) {
                <span class="tag">{{ team }}</span>
              }
            </li>
          }
        </ul>
      } @else {
        <p class="empty">Nobody matches “{{ query }}”.</p>
      }
      <ng-container ngProjectAs="[footer]">
        <button class="button" (click)="clear()">Clear</button>
      </ng-container>
    </mx-card>
  `,
})
export class Team {
  @Input() members: Member[] = [];
  protected query = "";

  protected get shown() {
    return this.members.filter((member) => member.name.includes(this.query));
  }

  protected search(event: Event) {
    this.query = (event.target as HTMLInputElement).value;
  }

  protected clear() {
    this.query = "";
  }
}
