// packages/hosts/solid/src/index.ts
import {
  type AttrTagConfig,
  type AttrTagOf,
  createTargetLookup,
  registerCalleeInputReader,
  type TargetLookup,
} from "@mxlang/core";
import type { Element as SolidElement } from "solid-js";
import { readSolidCalleeInput } from "./callee-reader.ts";
import {
  type CompileSolidMxOptions,
  type CompileSolidMxResult,
  compileSolidMx as compileRegion,
  compileSolidUnit as compileUnit,
} from "./compile.ts";
import descriptor from "./descriptor.ts";

export type { AttrTagConfig, AttrTagOf } from "@mxlang/core";
export type {
  CompileSolidMxOptions,
  CompileSolidMxResult,
  HoistedDefine,
  HoistedImport,
  RawSourceMap,
} from "./compile.ts";
export {
  createEmitter,
  emitSolid,
  emitSolidWithMappings,
  MX_ESCAPE_BINDING,
  MX_RETURN_PROP,
  SolidEmitter,
  solidDeclarations,
} from "./emitter.ts";
export { appendSolidBuiltinImport } from "./typecheck-module.ts";

/** Attribute-tag value specialised to Solid's reusable accessor renderable. */
export type AttrTag<
  // biome-ignore lint/complexity/noBannedTypes: public default from decision 106
  C extends AttrTagConfig = {},
> = AttrTagOf<C, () => SolidElement>;

registerCalleeInputReader(".solid.mx", readSolidCalleeInput);

/** The package's own lookup, shared by direct entries (design note §5.1(c)). */
export const solidTargets: TargetLookup = createTargetLookup([descriptor]);

/** Compiles an MX region; defaults to the package's own lookup. */
export function compileSolidMx(
  source: string,
  options: CompileSolidMxOptions,
): CompileSolidMxResult {
  return compileRegion(source, {
    ...options,
    targets: options.targets ?? solidTargets,
  });
}

/** Compiles a whole MX tag unit; defaults to the package's own lookup. */
export function compileSolidUnit(
  source: string,
  options: CompileSolidMxOptions,
): CompileSolidMxResult {
  return compileUnit(source, {
    ...options,
    targets: options.targets ?? solidTargets,
  });
}

// packages/hosts/react/src/index.ts
import type {
  AttrTagConfig,
  AttrTagOf,
  CompileResult,
  RawSourceMap,
} from "@mxlang/core";
import { createTargetLookup, type TargetLookup } from "@mxlang/core";
import type { CompilePreactOptions, CompilePreactResult } from "@mxlang/preact";
import type { ReactNode } from "react";
import {
  compileReactFile as compileReactFileWith,
  compileReactMx as compileReactMxWith,
} from "./compile.ts";
import descriptor from "./descriptor.ts";

/**
 * This package's own target table (decisions 129 and 132): the one descriptor
 * it exports, defaulting for a direct entry that names no lookup of its own
 * (design note §5.1, rule (c)). The compile itself runs through
 * `@mxlang/preact`'s shared emitter, but the lookup a caller gets by default
 * is React's, so a callee importing `AttrTag` from `@mxlang/react` is
 * recognised the same as one from `@mxlang/preact`.
 */
const ownTargets: TargetLookup = createTargetLookup([descriptor]);

export { TranslateError } from "@mxlang/preact";
export { reactDeclarations, reactDialect } from "./dialect.ts";
export type { CompileResult, RawSourceMap };

/** Attribute-tag value specialised to React's renderable node type. */
export type AttrTag<
  // biome-ignore lint/complexity/noBannedTypes: public default from decision 106
  C extends AttrTagConfig = {},
> = AttrTagOf<C, ReactNode>;

/**
 * Compiles a whole-file MX template to a React component module.
 *
 * `options.targets` defaults to this package's own lookup; see
 * `@mxlang/preact`'s `CompilePreactOptions.targets`.
 */
export function compileReactMx(
  source: string,
  filename: string,
  options: Pick<
    CompilePreactOptions,
    "customTags" | "resolveImport" | "warnings" | "targets" | "typeCheck"
  > = {},
): CompilePreactResult {
  return compileReactMxWith(source, filename, {
    ...options,
    targets: options.targets ?? ownTargets,
  });
}

/** `compileReactMx()` over a file on disk. */
export function compileReactFile(
  filename: string,
  options: Pick<
    CompilePreactOptions,
    "customTags" | "resolveImport" | "warnings" | "targets" | "typeCheck"
  > = {},
): CompileResult {
  return compileReactFileWith(filename, {
    ...options,
    targets: options.targets ?? ownTargets,
  });
}
